export const ordersData = [
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 111",
  },
  {
    id: "728ed5211",
    title: "Заказ 2",
    status: "inactive",
    user: "Пользователь 2",
  },
  {
    id: "728ed52111",
    title: "Заказ 3",
    status: "new",
    user: "Пользователь 3",
  },
  {
    id: "728ed521111",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5212",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed52122",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521333",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521444",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed52154564",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5215567",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5215676",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5214346",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5215768",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5214346",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5216879",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed5213455667",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
  {
    id: "728ed521",
    title: "Заказ 1",
    status: "active",
    user: "Пользователь 1",
  },
];
